"""add_ledger_tables

Revision ID: 240bfb393ac9
Revises: c4de5c72a423
Create Date: 2025-06-22 20:35:00.071391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '240bfb393ac9'
down_revision: Union[str, Sequence[str], None] = 'c4de5c72a423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_analysis_results_discovery_id_fkey'), 'ai_analysis_results', type_='foreignkey')
    op.create_foreign_key(None, 'ai_analysis_results', 'host_discoveries', ['discovery_id'], ['id'])
    op.drop_index(op.f('idx_host_discoveries_confidence'), table_name='host_discoveries')
    op.drop_index(op.f('idx_host_discoveries_hostname'), table_name='host_discoveries')
    op.drop_index(op.f('idx_host_discoveries_protocol'), table_name='host_discoveries')
    op.drop_index(op.f('idx_host_discoveries_session'), table_name='host_discoveries')
    op.drop_index(op.f('idx_host_discoveries_timestamp'), table_name='host_discoveries')
    op.drop_constraint(op.f('host_discoveries_session_id_fkey'), 'host_discoveries', type_='foreignkey')
    op.create_foreign_key(None, 'host_discoveries', 'scan_sessions', ['session_id'], ['session_id'])
    op.drop_constraint(op.f('network_scan_data_discovery_id_fkey'), 'network_scan_data', type_='foreignkey')
    op.create_foreign_key(None, 'network_scan_data', 'host_discoveries', ['discovery_id'], ['id'])
    op.drop_index(op.f('idx_probe_results_discovery'), table_name='protocol_probe_results')
    op.drop_index(op.f('idx_probe_results_port'), table_name='protocol_probe_results')
    op.drop_index(op.f('idx_probe_results_type'), table_name='protocol_probe_results')
    op.drop_constraint(op.f('protocol_probe_results_discovery_id_fkey'), 'protocol_probe_results', type_='foreignkey')
    op.create_foreign_key(None, 'protocol_probe_results', 'host_discoveries', ['discovery_id'], ['id'])
    op.drop_column('protocol_probe_results', 'updated_at')
    op.drop_index(op.f('idx_scan_sessions_status'), table_name='scan_sessions')
    op.drop_index(op.f('idx_signature_matches_discovery'), table_name='signature_match_results')
    op.drop_index(op.f('idx_signature_matches_protocol'), table_name='signature_match_results')
    op.drop_index(op.f('idx_signature_matches_score'), table_name='signature_match_results')
    op.drop_constraint(op.f('signature_match_results_discovery_id_fkey'), 'signature_match_results', type_='foreignkey')
    op.create_foreign_key(None, 'signature_match_results', 'host_discoveries', ['discovery_id'], ['id'])
    op.create_foreign_key(None, 'signature_match_results', 'protocols', ['protocol_id'], ['id'])
    op.drop_index(op.f('idx_validation_accuracy'), table_name='validation_results')
    op.drop_constraint(op.f('validation_results_discovery_id_fkey'), 'validation_results', type_='foreignkey')
    op.create_foreign_key(None, 'validation_results', 'host_discoveries', ['discovery_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'validation_results', type_='foreignkey')
    op.create_foreign_key(op.f('validation_results_discovery_id_fkey'), 'validation_results', 'host_discoveries', ['discovery_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_validation_accuracy'), 'validation_results', ['detection_was_correct', 'validation_confidence'], unique=False)
    op.drop_constraint(None, 'signature_match_results', type_='foreignkey')
    op.drop_constraint(None, 'signature_match_results', type_='foreignkey')
    op.create_foreign_key(op.f('signature_match_results_discovery_id_fkey'), 'signature_match_results', 'host_discoveries', ['discovery_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_signature_matches_score'), 'signature_match_results', ['combined_final_score'], unique=False)
    op.create_index(op.f('idx_signature_matches_protocol'), 'signature_match_results', ['protocol_name'], unique=False)
    op.create_index(op.f('idx_signature_matches_discovery'), 'signature_match_results', ['discovery_id'], unique=False)
    op.create_index(op.f('idx_scan_sessions_status'), 'scan_sessions', ['status', 'started_at'], unique=False)
    op.add_column('protocol_probe_results', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'protocol_probe_results', type_='foreignkey')
    op.create_foreign_key(op.f('protocol_probe_results_discovery_id_fkey'), 'protocol_probe_results', 'host_discoveries', ['discovery_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_probe_results_type'), 'protocol_probe_results', ['probe_type'], unique=False)
    op.create_index(op.f('idx_probe_results_port'), 'protocol_probe_results', ['target_port'], unique=False)
    op.create_index(op.f('idx_probe_results_discovery'), 'protocol_probe_results', ['discovery_id'], unique=False)
    op.drop_constraint(None, 'network_scan_data', type_='foreignkey')
    op.create_foreign_key(op.f('network_scan_data_discovery_id_fkey'), 'network_scan_data', 'host_discoveries', ['discovery_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'host_discoveries', type_='foreignkey')
    op.create_foreign_key(op.f('host_discoveries_session_id_fkey'), 'host_discoveries', 'scan_sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.create_index(op.f('idx_host_discoveries_timestamp'), 'host_discoveries', ['scan_completed_at'], unique=False)
    op.create_index(op.f('idx_host_discoveries_session'), 'host_discoveries', ['session_id'], unique=False)
    op.create_index(op.f('idx_host_discoveries_protocol'), 'host_discoveries', ['detected_protocol'], unique=False)
    op.create_index(op.f('idx_host_discoveries_hostname'), 'host_discoveries', ['hostname'], unique=False)
    op.create_index(op.f('idx_host_discoveries_confidence'), 'host_discoveries', ['confidence_level', 'confidence_score'], unique=False)
    op.drop_constraint(None, 'ai_analysis_results', type_='foreignkey')
    op.create_foreign_key(op.f('ai_analysis_results_discovery_id_fkey'), 'ai_analysis_results', 'host_discoveries', ['discovery_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
